# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Modifiy the specific files using scripts
        run: |
          touch Client.jar.md5
          touch Client.json.md5
          md5sum Client.jar > Client.jar.md5
          md5sum Client.json > Client.json.md5
      - name: Modifiy the specific files using action
        uses: action-owner/action-repo@ref
      - name: Run it
        run: |
          git config --global user.name "Github Actions"

          git add Client.jar.md5
          git add Client.json.md5
          git commit -m "Github Acions"
          git push
