# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Modifiy the specific files using scripts
        run: |
          touch Client.jar.md5
          touch Client.json.md5
          md5sum Client.jar > Client.jar.md5
          md5sum Client.json > Client.json.md5
          sed -i 's/  Client.jar//' Client.jar.md5
          sed -i 's/  Client.json//' Client.json.md5
      - name: Run it
        run: |
          git config --global user.name "Github Actions"

          git add Client.jar.md5
          git add Client.json.md5
          git commit -m "Get MD5 hash"
          git push
